package app.movia.android.domain.model

enum class ContentType(val label: String) {
    MOVIE("Фильмы"),
    SERIES("Сериалы"),
    TV("ТВ"),
}

enum class CatalogCategory(val label: String) {
    MOVIES("Фильмы"),
    TV_SERIES("Сериалы"),
    LIMITED_SERIES("Мини-сериалы"),
    ANIMATION("Анимация"),
    ANIME("Аниме"),
    DRAMAS_ASIAN("Дорамы"),
    DOCUMENTARIES("Документальные"),
    THEATER_MUSICALS("Театр и мюзиклы"),
    STANDUP("Стендап"),
    INTERACTIVE("Интерактивное кино"),
}

data class Person(
    val name: String,
    val photoUrl: String? = null,
    val role: String? = null,
    val knownFor: List<String> = emptyList(),
)

data class StreamOption(
    val voice: String,
    val quality: String,
    val seeders: Int = 0,
    val url: String = "",
    val source: String? = null,
    val streamId: String = "",
    val providerItemId: String? = null,
    val infoHash: String? = null,
    val fileIndex: Int? = null,
    val filePath: String? = null,
    val seasonNumber: Int? = null,
    val episodeNumber: Int? = null,
    val mimeType: String? = null,
    val drmScheme: String? = null,
    val drmLicenseUrl: String? = null,
    val language: String = "ru",
    val codec: String? = null,
    val userAgent: String? = null,
    val headers: Map<String, String> = emptyMap(),
    val subtitles: List<StreamSubtitle> = emptyList(),
    val hasInternalSubtitles: Boolean = false,
    val videoTrackIndex: Int? = null,
    val audioTrackIndex: Int? = null,
    val durationMs: Long? = null,
    val sizeBytes: Long? = null,
    val reloadSupported: Boolean = false,
    val reloadData: String? = null,
    val sourceId: String? = null,
    val providerId: String? = null,
    val providerContentId: String? = null,
    val transport: String = "direct",
    val transportMetadata: Map<String, String> = emptyMap(),
    val resolution: String? = null,
    val unavailableQuality: Boolean = false,
    val isTrailer: Boolean = false,
    val downloadUrl: String? = null,
    val downloadHeaders: Map<String, String> = emptyMap(),
    val skipIntervals: List<StreamSkipInterval> = emptyList(),
    val advertisement: StreamAdvertisement? = null,
    val catalogMediaId: String? = null,
    val canonicalTitle: String? = null,
    val canonicalYear: Int? = null,
    val canonicalMediaType: ContentType? = null,
    val healthScore: Double = 0.5,
    val startupLatencyMs: Long? = null,
    val recentFailureCount: Int = 0,
    val providerReliability: Double? = null,
)

data class MediaContent(
    val id: String,
    val title: String,
    val type: ContentType,
    val year: Int,
    val rating: Double,
    val genres: Set<String>,
    val country: String,
    val quality: String,
    val durationMinutes: Int,
    val isNew: Boolean = false,
    val popularity: Int = 0,
    val ageRating: Int = 16,
    val audioLanguages: Set<String> = setOf("Original"),
    val subtitleLanguages: Set<String> = emptySet(),
    val originalTitle: String? = null,
    val director: String? = null,
    val cast: List<Person> = emptyList(),
    val synopsis: String? = null,
    val seasonEpisodeCounts: List<Int> = emptyList(),
    val relatedContentIds: List<String> = emptyList(),
    val sequelPrequelIds: List<String> = emptyList(),
    val imdbRating: Double? = null,
    val category: CatalogCategory = CatalogCategory.MOVIES,
    val sourceUrl: String? = null,
    val playbackUrl: String? = null,
    val posterUrl: String? = null,
    val backdropUrl: String? = null,
    val licenseName: String? = null,
    val licenseUrl: String? = null,
    val streams: List<StreamOption> = emptyList(),
    val voteCount: Int = 0,
    val seasonsCount: Int = 0,
    val episodesCount: Int = 0,
)
